name: Append schema.json to Release

on:
  workflow_run:
    workflows:
      - Validate Code with Tests
    types:
      - completed

permissions:
  contents: write

jobs:
  append-schema:
    name: Append schema.json to Release
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}  # Only allow release from the main branch and if tests passed
    
    steps:
      - name: '📦 Add schema.json'
        run: gh release upload ${{ github.event.release.tag_name }} schema.json        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}