name: Append schema.json to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test-code:
    name: Run Bun Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Bun Tests
        run: bun test

  append-schema:
    name: Append schema.json to Release
    runs-on: ubuntu-latest
    needs: test-code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: '📦 Add schema.json'
        run: gh release upload ${{ github.event.release.tag_name }} schema.json        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}